### ISSUE TITLE
Views with Ajax pagers don't filter correctly on D8

### ISSUE THREAD

**Issue by milkovsky** [drunomics/views_exclude_previous#3]
Smth like this should help: https://www.drupal.org/project/views_exclude_previous/issues/2904285

**Comment by milkovsky** [comment]
Potential problem: it will not make sense to cache such ajax requests (https://www.drupal.org/project/ajax_assets_plus).
Every ajax request will contain the excluded ids array.

**Comment by fago** [comment]
I think the problem is that the excluded IDs are not passed to the ajax request, thus lost during the processing of the pages. I'm not sure how caching plays into this - are you experiencing the problem only for cached responses?

**Comment by milkovsky** [comment]
Yes, we should pass a GET parameter with all the excluded IDs. Smth like: `...&views_exclude_previous=111,222,333`.
Let's assume Ajax requests are GET and cached.
The parameter value will be different on every request. It will generate a lot of unique GET requests, thus increase cache size.

**Comment by milkovsky** [comment]
Hmm... once I wrote this, I do not see a problem anymore :-D Every pager ajax request is anyway unique, because it has page number there.
